./gradlew\
    anko-core:publishReleasePublicationToSonatypeRepository\
    anko-coroutines:publishReleasePublicationToSonatypeRepository\
    anko-mvvm:publishReleasePublicationToSonatypeRepository\
    anko-rx:publishReleasePublicationToSonatypeRepository\
    core:publishReleasePublicationToSonatypeRepository\
    core-design:publishReleasePublicationToSonatypeRepository\
    core-mvvm:publishReleasePublicationToSonatypeRepository\
    core-recycler:publishReleasePublicationToSonatypeRepository\
    local-core:publishReleasePublicationToSonatypeRepository\
    local-recycler:publishReleasePublicationToSonatypeRepository\
    local-design:publishReleasePublicationToSonatypeRepository\
    rx2-core:publishReleasePublicationToSonatypeRepository\
    rx2-design:publishReleasePublicationToSonatypeRepository\
    rx2-mvvm:publishReleasePublicationToSonatypeRepository\
    rx2-recycler:publishReleasePublicationToSonatypeRepository\
    rx2-swiperefreshlayout:publishReleasePublicationToSonatypeRepository\
    coroutines-core:publishReleasePublicationToSonatypeRepository\
    coroutines-design:publishReleasePublicationToSonatypeRepository\
    coroutines-swiperefreshlayout:publishReleasePublicationToSonatypeRepository\
    coroutines-recycler:publishReleasePublicationToSonatypeRepository\